[project]
name = "xclient"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.2",
    "pydantic>=2.10.0",
]

[tool.setuptools.packages.find]
include = ["xclient*"]
